/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package volume.beratbadan;

import javax.swing.JOptionPane;

/**
 *
 * @author Hyung
 */
public class BeratBadan extends javax.swing.JFrame {
    
    String temp ="";
    Double ti, bt, h1;
    
    /**
     * Creates new form BeratBadan
     */
    public BeratBadan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        bb = new javax.swing.JTextField();
        boy = new javax.swing.JRadioButton();
        grill = new javax.swing.JRadioButton();
        hitung = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bbi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 150, 20);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 50, 40, 20);

        jLabel3.setText("Tinggi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 90, 40, 20);

        jLabel4.setText("Berat Badan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 130, 80, 20);

        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 170, 80, 10);
        jPanel1.add(nama);
        nama.setBounds(170, 40, 140, 30);
        jPanel1.add(tinggi);
        tinggi.setBounds(170, 80, 80, 30);
        jPanel1.add(bb);
        bb.setBounds(170, 120, 80, 30);

        boy.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup1.add(boy);
        boy.setText("Laki-laki");
        jPanel1.add(boy);
        boy.setBounds(170, 150, 80, 30);

        grill.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup1.add(grill);
        grill.setText("Perempuan");
        jPanel1.add(grill);
        grill.setBounds(170, 170, 100, 30);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel1.add(hitung);
        hitung.setBounds(80, 200, 70, 30);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(160, 200, 90, 30);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(260, 200, 60, 30);

        jLabel6.setText("Berat badan ideal Anda adalah");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 250, 170, 20);
        jPanel1.add(bbi);
        bbi.setBounds(260, 240, 60, 30);

        jLabel7.setText("Hasil diagnosa Anda yaitu :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 270, 150, 20);

        result.setEditable(false);
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        jPanel1.add(result);
        result.setBounds(20, 290, 370, 30);

        saran.setEditable(false);
        jPanel1.add(saran);
        saran.setBounds(20, 350, 370, 30);

        jLabel8.setText("Saran dari kami :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 330, 100, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 390);

        setSize(new java.awt.Dimension(426, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        if (nama.getText().equals("")||tinggi.getText().equals("")
                ||bb.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Mohon isi datanya, Mas / Mbak");
    }
                else if (boy.isSelected()|| grill.isSelected()){
                        try {
                        Process();
                        }catch (Exception e){
                        JOptionPane.showMessageDialog(null, "Masih ada yang kosong, Mas / Mbak");
                        }
                }
                        else{
                        JOptionPane.showMessageDialog(null,"Mas / Mbak, jenis kelaminnya?");
                        }
    }//GEN-LAST:event_hitungActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
                nama.setText("");
        tinggi.setText("");
        bb.setText("");
        buttonGroup1.clearSelection();
        bbi.setText("");
        result.setText("");
        saran.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeratBadan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bb;
    private javax.swing.JTextField bbi;
    private javax.swing.JRadioButton boy;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton grill;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nama;
    private javax.swing.JButton reset;
    private javax.swing.JTextField result;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Process() {
        ti = Double.parseDouble(tinggi.getText());
    bt = Double.parseDouble(bb.getText());
    
    if (boy.isSelected()) {
    h1 = (ti - 100) * 1;
    }else if (grill.isSelected()){
    h1 = (ti - 104) * 1;
    }
    temp = Double.toString(h1.intValue());
    if (h1<bt) {
    
        bbi.setText(temp);
        result.setText ("Sepurane masbro / mbaksis " + nama.getText() + ", Sampeyan *ehm LEMU");
        saran.setText ("Banyakin Berolahraga dan hindari makanan berkolesterol");
    }else if (h1>bt) {
    
        bbi.setText(temp);
        result.setText ("Pangapunten masbro / mbaksis " + nama.getText() + ", Panjenengan *ehm CUNGKRING");
        saran.setText ("Banyakin mengkonsumsi makanan yang berkarbohidrat");
    }else {
    
        bbi.setText(temp);
        result.setText ("Mantab " + nama.getText() + ", berat'e sampeyan pas");
        saran.setText ("LANJOETKAN");
    }
    }
    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (nama.getText().equals("")||tinggi.getText().equals("")
                ||bb.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Data Harus Diisi Semua");
    }
                else if (boy.isSelected()||grill.isSelected()){
                        try {
                        Process();
                        }catch (Exception e){
                        JOptionPane.showMessageDialog(null, "Inputan ada yang belum diisi");
                        }
                }
                        else{
                        JOptionPane.showMessageDialog(null,"Radio Button Harus Dipilih");
                        }
    }
}
