/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package volume.beratbadan;

import javax.swing.JOptionPane;

/**
 *
 * @author Hyung
 */
public class Volume extends javax.swing.JFrame {

    /**
     * Creates new form Volume
     */
    public Volume() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        balokpjg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        baloklbr = new javax.swing.JTextField();
        baloktgg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        resultbalok = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        kubussisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        resultkubus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jarjarbol = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        resultlbola = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);
        jPanel2.add(balokpjg);
        balokpjg.setBounds(150, 20, 150, 30);

        jLabel1.setText("Masukkan Panjang");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 30, 110, 20);

        jLabel2.setText("Masukkan Lebar");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 70, 100, 20);

        jLabel3.setText("Masukkan Tinggi");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 110, 100, 20);
        jPanel2.add(baloklbr);
        baloklbr.setBounds(150, 60, 150, 30);
        jPanel2.add(baloktgg);
        baloktgg.setBounds(150, 100, 150, 30);

        jLabel4.setText("cm");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(300, 110, 30, 20);

        jLabel5.setText("cm");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(300, 30, 30, 20);

        jLabel6.setText("cm");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(300, 70, 30, 20);

        resultbalok.setText("HITUNG");
        resultbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultbalokActionPerformed(evt);
            }
        });
        jPanel2.add(resultbalok);
        resultbalok.setBounds(150, 140, 80, 30);

        jTabbedPane1.addTab("Balok", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setLayout(null);

        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 30, 130, 20);

        kubussisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kubussisiActionPerformed(evt);
            }
        });
        jPanel3.add(kubussisi);
        kubussisi.setBounds(40, 60, 170, 30);

        jLabel9.setText("cm");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(210, 70, 30, 20);

        resultkubus.setText("HITUNG");
        resultkubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultkubusActionPerformed(evt);
            }
        });
        jPanel3.add(resultkubus);
        resultkubus.setBounds(40, 100, 80, 30);

        jTabbedPane1.addTab("Kubus", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 153, 51));
        jPanel4.setLayout(null);

        jLabel10.setText("Masukkan Panjang Jari-Jari");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(40, 30, 150, 20);
        jPanel4.add(jarjarbol);
        jarjarbol.setBounds(40, 60, 170, 30);

        jLabel11.setText("cm");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(210, 70, 30, 20);

        resultlbola.setText("HITUNG");
        resultlbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultlbolaActionPerformed(evt);
            }
        });
        jPanel4.add(resultlbola);
        resultlbola.setBounds(40, 100, 80, 30);

        jTabbedPane1.addTab("Bola", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 40, 400, 230);

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Program Penghitung Volume Bangun Ruang");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 0, 320, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 60);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resultbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultbalokActionPerformed
        // TODO add your handling code here:
        int longs, width, height;
        longs = Integer.parseInt(balokpjg.getText());
        width = Integer.parseInt(baloklbr.getText());
        height = Integer.parseInt(baloktgg.getText());
        int result = longs*width*height;
        
        try {
            JOptionPane.showMessageDialog(null,"Volume balok adalah : "+result,"Luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, " Error"+e,"Failure", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_resultbalokActionPerformed

    private void kubussisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kubussisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kubussisiActionPerformed

    private void resultkubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultkubusActionPerformed
        // TODO add your handling code here:
        int side;
        side = Integer.parseInt(kubussisi.getText());
        int result = side*side*side;
        
        try{
            JOptionPane.showMessageDialog(null,"Volume kubus adalah : "+result, "Luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR : "+e, "Failure", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_resultkubusActionPerformed

    private void resultlbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultlbolaActionPerformed
        // TODO add your handling code here:
        float fingers;
        fingers = Integer.parseInt(jarjarbol.getText());
        float result = 4/3 * 22/7 * fingers * fingers * fingers;
        
        try {
            JOptionPane.showMessageDialog(null,"Volume balok adalah : "+result, "luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
               JOptionPane.showMessageDialog(null,"ERROR : "+e, "FAILURE", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_resultlbolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baloklbr;
    private javax.swing.JTextField balokpjg;
    private javax.swing.JTextField baloktgg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jarjarbol;
    private javax.swing.JTextField kubussisi;
    private javax.swing.JButton resultbalok;
    private javax.swing.JButton resultkubus;
    private javax.swing.JButton resultlbola;
    // End of variables declaration//GEN-END:variables
}
